name: Rebase
on:
  schedule:
    - cron:  '40 7 * * *'
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v4
        with:
          exclude-labels: |
            no-rebase
            dependencies
          # exclude-drafts: true
